version: "3.4"
services:
  react-app:
    image: react-app
    container_name: react-app
    tty: true
    build:
      context: react-app
      target: prod
    environment:
      NODE_ENV: development
      LISTENING_PORT: ${REACT_APP_LISTENING_PORT}
      REACT_APP_AUTH_SERVICE_URL: http://auth-service:${AUTH_SERVICE_LISTENING_PORT}
      REACT_APP_CHARACTER_SERVICE_URL: http://character-service:${CHARACTER_SERVICE_LISTENING_PORT}
    ports:
      - 3000:${REACT_APP_LISTENING_PORT}
    depends_on:
      - auth-service
      - character-service
    command: ["npm", "run", "build"]
  character-service:
    image: character-service
    container_name: character-service
    build:
      context: character-service
      target: prod
    environment:
      NODE_ENV: production
      MONGO_URL: ${MONGO_URL}
      LISTENING_PORT: ${USER_SERVICE_LISTENING_PORT}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
    ports:
      - 3000:${USER_SERVICE_LISTENING_PORT}
    depends_on:
      - mongo
    command: ["node", "build/index.js"]
  auth-service:
    image: auth-service
    container_name: auth-service
    build:
      context: auth-service
      target: prod
    environment:
      NODE_ENV: production
      MONGO_URL: ${MONGO_URL}
      LISTENING_PORT: ${AUTH_SERVICE_LISTENING_PORT}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ACCESS_TOKEN_EXPIRATION_TIME: ${ACCESS_TOKEN_EXPIRATION_TIME}
      AUTH_COOKIE_MAX_AGE: ${AUTH_COOKIE_MAX_AGE}
      ENCRYPTION_SALT_ROUNDS: ${ENCRYPTION_SALT_ROUNDS}
    ports:
      - 3001:${AUTH_SERVICE_LISTENING_PORT}
    depends_on:
      - mongo
    command: ["node", "build/index.js"]
  mongo:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/mongodb/config/mongod.conf:/etc/mongod.conf
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./.docker/mongodb/data/db/:/data/db/
      #- ./.docker/mongodb/data/log/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
    command: ["-f", "/etc/mongod.conf"]
    healthcheck:
      test: '[ `echo ''db.runCommand("ping").ok'' | mongo localhost/${MONGO_INITDB_DATABASE} --quiet` ] && echo 0 || echo 1'
      interval: 5s
      start_period: 10s
      timeout: 4s
      retries: 3
volumes:
  notused:
