export const GET_CHARACTERS = '@@CHARACTER_LIST/GET_CHARACTERS';
export const GET_FILTERED_CHARACTERS = '@@CHARACTER_LIST/GET_FILTERED_CHARACTERS';
export const TOGGLE_FAVORITE = '@@CHARACTER_LIST/TOGGLE_FAVORITE';
export const APPLY_PATCHES = '@@CHARACTER_LIST/APPLY_PATCHES';
